### ISSUE TITLE
Image preview does not change

### ISSUE THREAD

**Issue by VLDrenth** [aalfons/robmedExtra#14]
In the `export` tab, the changes to image quality do not seem to be reflected in the displayed preview. An extreme example of setting the image quality to 1 pixel per inch still gives a legible preview, but the actual export consists of only a few pixels.

**Comment by aalfons** [comment]
In the shiny app, we can't (easily) show a direct representation of the size and resolution of the selected file. As the browser displays all the content with a certain resolution (defined by the display settings of the operating system) that is independent of what the user selects here, the size of the file preview would be very hard to control. In addition, keep in mind that the resolution setting only applied to one of the available file types (png), while the pdf file is a vector graphic. The goal of the preview is just to give the user an idea of the proportions of the file, line and font sizes, etc.

We can, however, add a note that the resolution of the preview doesn't reflect the selected resolution for the png file.
