### ISSUE TITLE
How to plot the path diagram with results ?

### ISSUE THREAD

**Issue by dengxuebin** [aalfons/robmedExtra#37]
Hi aalfons
     I found robmed was a very convenient package for mediation analysis, especially for building formula including multiple mediators. But I did not find the function to plot path diagram like following pictures .  Hope your reply, thanks a lot! 

![image](https://github.com/aalfons/robmed/assets/58458637/52cb4268-7e32-4733-b070-26c385196835)

**Comment by aalfons** [comment]
You're right, it seems that this function is not yet on CRAN. If you have package `devtools` installed, you can install a development version of `robmedExtra` with the command:

```
devtools::install_github("aalfons/robmedExtra", ref = "diagram")
```
But please note that this version of the package is still experimental.
